apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::357323381515:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-SYXM4MSK1KKJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
   - groups:
     - roboshop-trainee
     userarn: arn:aws:iam::357323381515:user/rishika
     username: rishika
   - groups:
     - roboshop-trainee
     userarn: arn:aws:iam::357323381515:user/daivik
     username: daivik
   - groups:
     - roboshop-admin
     userarn: arn:aws:iam::357323381515:user/moksha
     username: moksha
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-25T15:31:37Z"
  name: aws-auth
  namespace: kube-system
  uid: ad3f46fc-b69a-46c4-b296-0591ebf219d6


