apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::357323381515:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-0PNGQ868f01T
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::357323381515:user/rishika
      username: rishika
kind: ConfigMap
metadata:
  creationTimestamp: "2026-06-24T14:27:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1069"
  uid: ca6e5111-9e37-431e-9e09-4677f71afcc7


